[package]
name = "silly"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
cpal = "0.17.0"
hotpath = "0.9.2"
ollama-rs = "0.3.3"
rubato = "0.16.2"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
transcribe-rs = { version = "0.2.1", features = ["parakeet"] }
vad-rs = { git = "https://github.com/cjpais/vad-rs", version = "0.1.5", default-features = false }

[features]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
